//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class child
    {
        public child()
        {
            this.childparentrels = new HashSet<childparentrel>();
            this.saleshistories = new HashSet<saleshistory>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string nickName { get; set; }
        public Nullable<int> birthYear { get; set; }
        public Nullable<int> birthMonth { get; set; }
        public string gender { get; set; }
        public string comment { get; set; }
    
        public virtual ICollection<childparentrel> childparentrels { get; set; }
        public virtual ICollection<saleshistory> saleshistories { get; set; }
    }
}
