//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemuser
    {
        public systemuser()
        {
            this.saleshistories = new HashSet<saleshistory>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public Nullable<int> wtmsRoleId { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<sbyte> isActive { get; set; }
        public Nullable<System.DateTime> deactivatedAt { get; set; }
        public string comment { get; set; }
    
        public virtual ICollection<saleshistory> saleshistories { get; set; }
        public virtual wtmsrole wtmsrole { get; set; }
    }
}
