//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class userStatu
    {
        public userStatu()
        {
            this.parents = new HashSet<parent>();
        }
    
        public int id { get; set; }
        public string statusName { get; set; }
    
        public virtual ICollection<parent> parents { get; set; }
    }
}
