//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class child
    {
        public child()
        {
            this.saleshistories = new HashSet<saleshistory>();
        }
    
        public int id { get; set; }
        public Nullable<int> parentId { get; set; }
        public string name { get; set; }
        public Nullable<int> birthYear { get; set; }
        public Nullable<int> birthMonth { get; set; }
        public string gender { get; set; }
        public string comment { get; set; }
    
        public virtual parent parent { get; set; }
        public virtual ICollection<saleshistory> saleshistories { get; set; }
    }
}
