//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wtmsEntities : DbContext
    {
        public wtmsEntities()
            : base("name=wtmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<parent> parents { get; set; }
        public DbSet<wtmsrole> wtmsroles { get; set; }
        public DbSet<child> children { get; set; }
        public DbSet<saleshistory> saleshistories { get; set; }
        public DbSet<systemuser> systemusers { get; set; }
    }
}
