//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parent
    {
        public parent()
        {
            this.children = new HashSet<child>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string mobile { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> deactivateAt { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<child> children { get; set; }
    }
}
